# ---------------------------------------------------------------
#   Site Information And Theme Configuration Settings
#   language: zh-CN
# ---------------------------------------------------------------

## menu
menu:
- page: Spring Cloud|周立
  url: /
  icon: fa-home
- page: 分类
  url: /categories
  icon: fa-list
- page: 关于我
  url: /about
  icon: fa-user
- page: 归档
  url: /archives
  icon: fa-archive


## favicon
favicon: /favicon.ico

## Feed
rss: /atom.xml

## Carousel
carousel:
  img: 
  url: 

# 各个小工具的设置

## widgets
widgets:
  - search
  - notification
  - aboutme
  - social
  - category
  # - archive
  - tagcloud
  - friends

## 首页关于我设置
aboutme:
  image: /icons/wx.jpg
  author: 周立
  words: 《Spring Cloud与Docker微服务架构实战》作者<br/>

## 搜索
jsonContent:
  searchLocal: true
  searchGoogle: false
  posts:
    title: true
    text: true
    content: true
    categories: true
    tags: true

## 网站公告设置
notification: |-
            <p>
              <b>笔者微信</b>：jumping_me，欢迎加我<br/>
              <b>公众号</b>：请扫描我的头像<br/>
            </p>

## 社交设置
social:
 - name: GitHub
   icon: github
   href: //github.com/eacdy
 - name: Git@OSC
   icon: git
   href: //gitee.com/itmuch
 - name: 邮箱
   icon: envelope-o
   href: mailto:eacdy0000@126.com
 - name: RSS
   icon: feed
   href: /atom.xml

## 文章分类设置
cate_config:
   show_count: true
   show_current: true

## 文章归档设置
arch_config:
   type: 'monthly'
   format: 'YYYY年MM月'
   show_count: true
   order: -1

## 标签云设置
tagcloud:
  tag3d: false
  textColour: '#444'
  outlineMethod: 'block'
  outlineColour: '#FFDAB9'
  interval: 30
  freezeActive: true
  frontSelect: true
  reverse: true
  wheelZoom: false

## 友链设置
links:
  - 程序猿DD|翟永超: http://blog.didispace.com/
  - 泥瓦匠的博客: http://www.bysocket.com/
  - EdisonXu's Blog: http://edisonxu.org/
  - 梁桂钊的博客: http://blog.720ui.com/
  - 猿天地: http://cxytiandi.com/


# 主题自定义个性化配置

## 网站宣传语
branding:

## 设置banner背景图片
banner:
    img: 

## 首页列表底部面板
homePanel: true

## 缩略图自定义随机图片
defaultImgs:
  -

## 截取文章首页描述字数
excerptLength: 240

## 是否开启文章目录
toc: false

## 代码高亮配置
highlightTheme:

## bootstrap配置
bootstrap:

## ICON配置
fontAwesome:

## 文章过期提醒功能
warning:
  days: 30000
  text: '本文于%d天之前发表，文中内容可能已经过时。'

## 文章内声明
declaration:
  enable: true
  title: '转载声明'
  tip: '本博客由周立创作，采用
    <a href="https://creativecommons.org/licenses/by-nc-nd/3.0/" target="_blank">
    CC BY 3.0 CN
    </a>
    许可协议。可自由转载、引用，但需署名作者且注明文章出处。如转载至微信公众号，请在文末添加作者公众号二维码。'

## 文章打赏
reward:
  alipay: ''
  wepay: ''
  tip: 

## 主题评论

### gitment
gitment:
  enable: true
  owner:
  repo: https://github.com/itmuch/hexo-itmuch-comment.git
  client_id: d7e519da38702d1a89c7
  client_secret: 9855c6abfbe45feedfc57168ff50ca7848bb88c4
  perPage: 10

### 来必力
livere:
  enable: false
  livere_uid: MTAyMC8zMzA1MS85NjEz

### 友言评论(服务不稳定)
uyan:
  enable: false
  uyan_id: 1966422

### Disqus评论
disqus:
  enable: false
  shortname: snippet
  count: false

### 畅言评论(需要ICP备案)
changyan:
  enable: false
  appid:
  conf:

## Valine评论
valine:
   enable: false
   appId: xOKV9J4UeQAtVkvnJC7Kq2Jn-gzGzoHsz
   appKey: erIpQac4azoCmgfBB7Dl9maa
   placeholder: 说点什么吧
   notify: false
   verify: false
   avatar: mm
   meta: nick,mail
   pageSize: 10

## 网站访客统计
visit_counter:
   site: true
   page: true

## 网站访问统计分析

### 网盟CNZZ统计
cnzz_analytics: 

### 百度统计
baidu_analytics: 13766878cde148282622871dd245a973

### 谷歌统计
google_analytics:

### 腾讯分析
tencent_analytics:

### 百度站点认证
baidu_site_verification:

### 百度自动推送
baidu_push: false

#网站主题配置
since: 2016
robot: 'all' ### 控制搜索引擎的抓取和索引编制行为，默认为all
version: 1.2.1
# 是否开启fork me on github
fork_me_on_github:
  enabled: true
  url: http://github.com/eacdy